[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true

[profile.default.metadata]
bytecode_hash = "ipfs"

[profile.default.evm_version]
version = "paris"

[profile.default.gas_reports]
"*" = ["*"]

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }

